/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config apps/api/wrangler.jsonc --include-runtime=false apps/api/types/cloudflare-env.d.ts` (hash: 6f5a44fbeb141f8d146a4847dadd7d94)
declare namespace Cloudflare {
  interface DevEnv {
    APP_DB: D1Database;
    MAILER: SendEmail;
    ENVIRONMENT: "development";
    APP_NAME: "GSU Build Day Techie Workshop";
    APP_ORIGIN: "http://localhost:5173";
    ALLOWED_ORIGINS: "http://localhost:5173,http://127.0.0.1:5173";
    EMAIL_FROM: "noreply@updates.example.com";
    EMAIL_REPLY_TO: "support@example.com";
  }
  interface StagingEnv {
    APP_DB: D1Database;
    MAILER: SendEmail;
    ENVIRONMENT: "staging";
    APP_NAME: "GSU Build Day Techie Workshop";
    APP_ORIGIN: "https://staging.example.com";
    ALLOWED_ORIGINS: "https://staging.example.com";
    EMAIL_FROM: "noreply@updates.example.com";
    EMAIL_REPLY_TO: "support@example.com";
  }
  interface PreviewEnv {
    APP_DB: D1Database;
    MAILER: SendEmail;
    ENVIRONMENT: "preview";
    APP_NAME: "GSU Build Day Techie Workshop";
    APP_ORIGIN: "https://preview.example.com";
    ALLOWED_ORIGINS: "https://preview.example.com";
    EMAIL_FROM: "noreply@updates.example.com";
    EMAIL_REPLY_TO: "support@example.com";
  }
  interface Env {
    APP_DB: D1Database;
    MAILER: SendEmail;
    ENVIRONMENT: "development" | "staging" | "preview" | "production";
    APP_NAME: "GSU Build Day Techie Workshop";
    APP_ORIGIN:
      | "http://localhost:5173"
      | "https://staging.example.com"
      | "https://preview.example.com"
      | "https://example.com";
    ALLOWED_ORIGINS:
      | "http://localhost:5173,http://127.0.0.1:5173"
      | "https://staging.example.com"
      | "https://preview.example.com"
      | "https://example.com";
    EMAIL_FROM: "noreply@updates.example.com";
    EMAIL_REPLY_TO: "support@example.com";
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<
        Cloudflare.Env,
        | "ENVIRONMENT"
        | "APP_NAME"
        | "APP_ORIGIN"
        | "ALLOWED_ORIGINS"
        | "EMAIL_FROM"
        | "EMAIL_REPLY_TO"
      >
    > {}
}
